apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  namespace: external-services
spec:
  selector:
    matchLabels:
      app: front-service
  replicas: 1
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: nattystar/house-rental:latest3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace:  external-services
spec:
  ports:
    - protocol: "TCP"
      # nodePort: 300
      port: 3000
      targetPort: 3000 
  selector:
    app: front-service
  type: LoadBalancer